project:
  type: website
  resources:
    - "resources/*"
  preview:
    port: 3000
    browser: true

format:
  html:
    css: 
      - styles.css
    toc: true
    theme: 
      light: cosmo
  revealjs:
    slide-level: 2
    theme: simple
    smaller: true
    code-overflow: scroll
    scrollable: true
    footer: "Informatica (30717) - Estudios en Arquitectura (UNIZAR)"
    auto-animate: true
    incremental: true
    show-slide-number: all
    code-line-numbers: true
    output-ext: "reveal.html"

website:
  title: "Informática (30717) - Grado en Estudios en Arquitectura"
  description: "Material de prácticas del curso 2025-2026."
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/informatica-30717/informatica-30717.github.io
  navbar:
    background: primary
    search: true
    right:
      - href: https://moodle.unizar.es/add/course/view.php?id=153600
        text: "![](../resources/unizar_white.png){width=95px}"
  sidebar:
    style: floating
    logo: ../resources/unizar.png

execute:
  freeze: auto

metadata-files:
  - sidebar.yml

lang: es