project:
  type: website
  resources:
    - "resources/*"
  preview:
    port: 3000
    browser: true

format:
  html:
    theme: cosmo
    css: 
      - styles.css
    toc: true

website:
  title: "Informática (30717) - Grado en Estudios en Arquitectura"
  description: "Material de prácticas del curso 2025-2026."
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/informatica-30717/informatica-30717.github.io
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/informatica-30717/informatica-30717.github.io
  sidebar:
    style: floating
    logo: ../resources/unizar.png

execute:
  freeze: auto

metadata-files:
  - sidebar.yml