project:
  type: website
  resources:
    - "resources/*"
  preview:
    port: 3000
    browser: true

format:
  html:
    css: 
      - styles.css
    toc: true
    theme: 
      light: cosmo

website:
  title: "Informática (30717) - Grado en Estudios en Arquitectura"
  description: "Material de prácticas del curso 2025-2026."
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/informatica-30717/informatica-30717.github.io
  navbar:
    background: primary
    search: true
    right:
      - href: https://moodle.unizar.es/add/course/view.php?id=153600
        text: "![](../resources/unizar_white.png){width=95px}"
  sidebar:
    style: floating
    logo: ../resources/unizar.png
  page-footer:
    left: |
      © 2026 Alfonso López Ruiz  
      Universidad de Zaragoza
    right: |
      Material docente protegido.  
      Licencia **CC BY-NC-SA 4.0** ![](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png){width=80px}  
      Uso docente no comercial permitido con atribución y licencia compartida.

license: "CC BY-NC-SA 4.0"

execute:
  freeze: auto

metadata-files:
  - sidebar.yml

lang: es